[package]
name = "gtp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "gtp-cli"
path = "src/main.rs"

[dependencies]
gtp-types = { workspace = true }
gtp-wire = { workspace = true }
gtp-core = { workspace = true }
gtp-sim = { workspace = true }
gtp-io = { workspace = true }
gtp-runtime-tokio = { workspace = true }
gtp = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
