[package]
name = "gtp-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gtp-types = { workspace = true }
socket2 = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = ["std"]
std = ["gtp-types/std"]
